version = 0.1
[default.deploy.parameters]
stack_name = "WeiAppDev"
resolve_s3 = true
s3_prefix = "WeiAppDev"
region = "eu-west-3"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
image_repositories = []
confirm_changeset = false
parameter_overrides = "StageParameter=\"dev\" WeiAppPictureStorageBucketName=\"wei-app-picture-storage\" SESMailAddressArn=\"arn:aws:ses:eu-west-3:704678314289:identity/no-reply.wei@isati.org\""
